# Generated by Django 5.1.2 on 2024-11-07 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('description', models.TextField(blank=True)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_templates', to='schoolcalendar.quarter')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='schoolcalendar.schoolyear')),
            ],
        ),
        migrations.AddField(
            model_name='quarter',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='schoolcalendar.term'),
        ),
        migrations.CreateModel(
            name='PeriodContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=100)),
                ('content_id', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('period_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='schoolcalendar.periodtemplate')),
            ],
            options={
                'unique_together': {('content_type', 'content_id', 'period_template')},
            },
        ),
    ]
