# Generated by Django 5.1.2 on 2024-11-08 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schoolcalendar', '0004_rename_term_structure_schoolyear_term_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodcontent',
            options={'ordering': ['date', 'period_number', '-priority']},
        ),
        migrations.AlterUniqueTogether(
            name='periodcontent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='periodcontent',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='periodcontent',
            name='display_mode',
            field=models.CharField(choices=[('SCHEDULE', 'Schedule View'), ('STANDALONE', 'Standalone View')], default='SCHEDULE', max_length=10),
        ),
        migrations.AddField(
            model_name='periodcontent',
            name='period_number',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='periodcontent',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='periodcontent',
            name='related_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='periodcontent',
            name='related_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodcontent',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='schoolcalendar.periodtemplate'),
        ),
        migrations.AlterField(
            model_name='periodcontent',
            name='content_type',
            field=models.CharField(choices=[('CLASS', 'Class Session'), ('MEETING', 'Meeting'), ('EVENT', 'School Event'), ('STUDY', 'Study Period'), ('EXAM', 'Examination'), ('DUTY', 'Staff Duty'), ('OTHER', 'Other Activity')], db_index=True, default='OTHER', max_length=10),
        ),
        migrations.AddIndex(
            model_name='periodcontent',
            index=models.Index(fields=['date', 'period_number'], name='schoolcalen_date_be79f8_idx'),
        ),
        migrations.AddIndex(
            model_name='periodcontent',
            index=models.Index(fields=['content_type', 'priority'], name='schoolcalen_content_f5a1aa_idx'),
        ),
        migrations.RemoveField(
            model_name='periodcontent',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='periodcontent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='periodcontent',
            name='period_template',
        ),
        migrations.RemoveField(
            model_name='periodcontent',
            name='start_time',
        ),
    ]
