# Generated by Django 5.1.2 on 2024-11-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolcalendar', '0010_historicalperiodtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperiodtemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='periodtemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='periodtemplate',
            unique_together={('name', 'version')},
        ),
    ]
